name: Dry Run DNS

on: ["push", "pull_request"]

jobs:
  octodns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3"
          cache: "pip" # caches pip dependencies
      - name: Install OctoDNS
        run: pip install 'octodns==0.9.10'
      - name: Do a dry run
        run: ./bin/dry-run
        env:
          DNSIMPLE_ACCOUNT_NUMBER: ${{ secrets.DNSIMPLE_ACCOUNT_NUMBER }}
          DNSIMPLE_API_KEY: ${{ secrets.DNSIMPLE_API_KEY }}
